---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
spec:
  secretName: ingress-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - "grafana.staging.eun"
    - "alertmanager.demo.lab"
    - "prometheus.staging.eun"
    - "thanos.demo.lab"
    - "istio-prometheus.staging.eun"
    - "kiali.staging.eun"
    - "tracing.staging.eun"
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
