apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingressgw
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - "*.staging.eun"
    port:
      name: http2
      number: 80
      protocol: HTTP
