apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno
  namespace: kyverno
spec:
  template:
    spec:
      containers:
      - name: kyverno
        resources:
          limits:
            cpu: 1500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 106Mi
