---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: core
  name: core

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: core
  name: core
  namespace: core

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    istio-injection: enabled
    toolkit.fluxcd.io/tenant: core
  name: core-reconciler
  namespace: core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:core:reconciler
- kind: ServiceAccount
  name: core
  namespace: core

