---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: core
  namespace: core
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: core
  url: https://github.com/mfamador/gitops-demo-tenant-core

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: core
spec:
  interval: 5m0s
  path: ./
  prune: true
  serviceAccountName: core
  sourceRef:
    kind: GitRepository
    name: core

