apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: external-requests
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        config:
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:headers():add("x-external-request", "true")
            end
