---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-federation
  labels:
    app.kubernetes.io/name: istio-prometheus
    tier: cluster
spec:
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    params:
      'match[]':
      - '{__name__=~"workload:(.*)"}'
      - '{__name__=~"istio:(.*)"}'
      - '{__name__=~"pilot(.*)"}'
      - '{__name__=~"envoy(.*)"}'
      - '{__name__=~"go(.*)"}'
      - '{__name__=~"flagger(.*)"}'
    path: /federate
    targetPort: 9090
    honorLabels: true
    metricRelabelings:
    - sourceLabels: ["__name__"]
      regex: 'workload:(.*)'
      targetLabel: "__name__"
      action: replace
    - sourceLabels: ["__name__"]
      regex: "istio:(.*)"
      targetLabel: "__name__"
      action: replace
