apiVersion: builtin
kind: PatchTransformer
metadata:
  name: kustomization-env-transformer
patch: |-
  - op: replace
    path: /spec/path
    value: ./staging/westeurope
target:
  kind: Kustomization
