apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
bases:
- ../../base/monitoring
resources:
- alertmanager-vs.yaml
- grafana-vs.yaml
- prometheus-vs.yaml
- thanos-query-vs.yaml
