apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/monitoring
resources:
- manifests/alertmanager-vs.yaml
- manifests/grafana-vs.yaml
- manifests/prometheus-vs.yaml
- manifests/thanos-query-vs.yaml
