apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
spec:
  releaseName: gatekeeper
  chart:
    spec:
      chart: gatekeeper
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      version: "3.8.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
