apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
# - gatekeeper.yaml
- grafana.yaml
- kube-prometheus-stack.yaml
- loki-distributed.yaml
- namespace.yaml
- prometheus-adapter.yaml
- promtail.yaml
- tempo-distributed.yaml
# - thanos.yaml
# - mimir.yaml
