apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- namespace.yaml
# - alertmanager.yaml
- grafana.yaml
# - gatekeeper.yaml
- loki.yaml
# - prometheus.yaml
- prometheus-adapter.yaml
- prometheus-stack.yaml
- promtail.yaml
- tempo.yaml
- thanos.yaml
