apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "0.41.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
      interval: "15s"
      labels:
        tier: cluster
