apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
spec:
  releaseName: mimir
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "3.1.0-weekly.201"
  timeout: 10m0s
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    metaMonitoring:
      serviceMonitor:
        enabled: true
    minio:
      enabled: false
    mimir:
      structuredConfig:
        limits:
          accept_ha_samples: true
          ha_replica_label: prometheus_replica
