apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
spec:
  releaseName: prometheus-adapter
  chart:
    spec:
      chart: prometheus-adapter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "2.12.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    rules:
      default: false
    prometheus:
      url: http://prometheus-operated.monitoring.svc.cluster.local
