apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "3.9.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    config:
      lokiAddress: http://loki-loki-distributed-gateway.monitoring/loki/api/v1/push
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
    - key: kubernetes.azure.com/scalesetpriority
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
