apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-adapter
spec:
  releaseName: prometheus-adapter
  chart:
    spec:
      chart: prometheus-adapter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      # https://github.com/prometheus-community/helm-charts/issues/1739
      version: "3.3.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 5m
        memory: 80Mi
      limits:
        # CPU limits commented because of CPU throttling
        # cpu: 10m
        memory: 128Mi
    ## RULES
    rules:
      default: false

      # CUSTOM METRICS
      # HTTP REQUESTS TOTAL
      custom:
      - seriesQuery: 'istio_requests_total{destination_workload_namespace!="",pod!="",source_cluster="Kubernetes",destination_cluster="Kubernetes"}'
        resources:
          overrides:
            destination_workload_namespace:
              resource: "namespace"
            pod:
              resource: "pod"
        name:
          matches: "^(.*)_total"
          as: "${1}_per_second"
        metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)
      ## HTTP REQUESTS DURATION
      - seriesQuery: 'istio_request_duration_milliseconds_sum{destination_workload_namespace!="",pod!="",source_cluster="Kubernetes",destination_cluster="Kubernetes"}'
        resources:
          overrides:
            destination_workload_namespace:
              resource: "namespace"
            pod:
              resource: "pod"
        name:
          matches: "^(.*)_sum"
          as: "${1}_avg"
        metricsQuery: avg(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)

      # EXTERNAL CUSTOM METRICS
      # CONSUMER LAG BR KAFKA-EXOIRTER
      external:
      - seriesQuery: 'kafka_consumergroup_lag_sum'
        metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (consumergroup, topic)
        resources:
          overrides:
            namespace:
              resource: "namespace"
          # setting `namespaced` to false we can get these metrics from any namespace
          namespaced: false
        name:
          as: "kafka_consumergroup_lag"

      ## MESSAGE LAG CALCULATED ON BENTHOS PIPELINES
      ## TODO add storage-queue-exporter metrics here
      - seriesQuery: 'benthos_storage__queue__message__lag'
        metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (queue)
        resources:
          overrides:
            namespace:
              resource: "namespace"
          # setting `namespaced` to false we can get these metrics from any namespace
          namespaced: false
        name:
          as: "storage_queue_message_lag"
