apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "0.9.6"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    storage:
      storageClassName: default
    traces:
      zipkin: true
      jaeger:
        thriftCompact: true
