apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "0.26.5"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: true
      jaeger:
        thriftHttp:
          enabled: true
        thriftCompact:
          enabled: true
      opencensus:
        enabled: true
    serviceMonitor:
      enabled: true
      interval: "15s"
      labels:
        tier: cluster
