apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
spec:
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      version: "1.21.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    leaderElection:
      enabled: true
      replicaCount: 1
    meshProvider: istio
    metricsServer: http://prometheus.istio-system:9090
    podMonitor:
      enabled: true
      additionalLabels:
        tier: istio
    rbac:
      create: true
    crd:
      create: false
    serviceAccount:
      create: true
