apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: manifests/charts/base
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
