apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- namespace.yaml
- flagger.yaml
- flagger-loadtester.yaml
- istio-base.yaml
- istio-operator.yaml
- kiali-operator.yaml
